import { GALLERY_TOKENS } from "../config/galleryTokens";

export const GALLERY_DEFAULTS = {
  scroll: {
    defaultStrength: 1,
    minStrength: 0.25,
    maxStrength: 8,
    baseSensitivity: 0.0007,
    legacyBaseSensitivity: 0.00024,
    legacySensitivityThreshold: 0.05,
  },
  corridor: {
    width: 8,
    height: 4.2,
    segmentLength: 12,
    carpetEnabled: false,
    carpetWidth: 0.72,
    carpetColor: GALLERY_TOKENS.artwork.defaultCarpet,
    artworkSpacing: 14,
    wallThickness: 0.24,
    artworkInset: 0.02,
  },
  artwork: {
    width: 2.4,
    height: 1.6,
    frameEnabled: false,
    frameColor: GALLERY_TOKENS.artwork.defaultFrame,
    frameThickness: 0.14,
    frameDepth: 0.06,
    spotlightIntensity: 1.5,
    sideTextWidth: 1.55,
    sideTextHeight: 1.1,
    sideTextGap: 0.5,
    sideTextOffsetY: 0,
    sideTextOffsetZ: 0,
    sideTextBorderEnabled: false,
    sideTextBorderColor: GALLERY_TOKENS.artwork.sideTextBorder,
    sideTextBorderIntensity: 1.2,
    sideTextBorderWidth: 0.035,
  },
  stationalCard: {
    width: 4,
    height: 2.5,
    depth: 0.05,
    backgroundColor: "#0d1018",
    borderColor: "rgba(255,255,255,0.08)",
    glowColor: "rgba(255,255,255,0.03)",
    spotlightIntensity: 1.35,
  },
  architecture: {
    stoneNormalScale: 0.72,
    ceilingNormalScale: 0.45,
    stoneTintMix: 0.72,
    wallTextureRepeatPerSegment: [1.35, 2] as const,
    floorTextureRepeatPerSegment: [8, 1.3] as const,
    ceilingTextureRepeatPerSegment: [8, 1.1] as const,
    wallRoughness: 0.88,
    floorRoughness: 0.72,
    ceilingRoughness: 0.88,
    nicheDepth: 0.25,
    nichePadding: 0.3,
    nicheTrimWidth: 0.12,
    nicheSurfaceClearance: 0.035,
    stationNicheWidthScale: 1.6,
    stationNicheHeightScale: 1.4,
    ceilingGridInset: 0.7,
    lightGridWidth: 6.6,
    lightGridMinWidth: 1.2,
    ceilingGridRailWidth: 0.035,
    ceilingGridRailMinWidth: 0.01,
    ceilingGridRailMaxWidth: 0.18,
    ceilingGridDepthSpacing: 4.2,
    ceilingGridFadeSegmentCount: 3.2,
    ceilingGridFadeSteps: 5,
    ceilingGridFadeMinOpacity: 0.04,
    ceilingFixtureRadius: 0.09,
    ceilingFixtureCoreRadius: 0.052,
    ceilingFixtureDepth: 0.026,
    maxCeilingSpotLights: 18,
    ceilingFillLightIntensity: 0.72,
    ceilingFillLightMaxIntensity: 4,
    ceilingFillLightWidthScale: 0.92,
    ceilingFillLightDepthScale: 1.04,
    ceilingFillLightInset: 0.38,
    ledStripThickness: 0.032,
    ledStripWallInset: 0.018,
    ledStripEdgeInset: 0.028,
    maxLedRakeLights: 16,
    ledRakeLightIntensity: 2.2,
    ledRakeLightDistance: 6.8,
    ledRakeLightWallInset: 0.16,
    ledFloorLightYOffset: 0.16,
    ledFloorLightIntensityScale: 1,
    ledVerticalLightHeightScale: 0.5,
    ledVerticalLightIntensityScale: 0.62,
    ledBakeSurfaceOffset: 0.018,
    ledBakeFloorWidth: 1.2,
    ledBakeVerticalWallWidth: 0.82,
    ledBakeWallEdgeHeight: 0.82,
    ledBakeFloorOpacity: 0.34,
    ledBakeWallOpacity: 0.24,
    ledBakeCeilingOpacity: 0.16,
  },
  timings: {
    introDuration: 1.1,
    travelDuration: 1,
    focusDuration: 0.9,
    returnDuration: 0.75,
  },
} as const;
