import { CAMERA_DEFAULTS } from "../constants/cameraDefaults";
import { GALLERY_DEFAULTS } from "../constants/galleryDefaults";
import type { ArtGallerySceneConfig, ArtworkConfig } from "../types/galleryConfig";
import { GALLERY_TOKENS } from "./galleryTokens";

const DEFAULT_ARTWORKS: ArtworkConfig[] = [
  {
    id: "w-01",
    type: "artwork",
    title: "Echoes of Atrium",
    description: "A suspended fragment of stillness.",
    imageUrl: "/images/work1.jpg",
    sideText: {
      eyebrow: "Gallery Note",
      title: "Echoes of Atrium",
      description: "A suspended fragment of stillness in atmospheric low-contrast tones.",
    },
    metadata: { artist: "A. Mercer", year: "2026", medium: "Archival Pigment" },
  },
  {
    id: "w-02",
    type: "artwork",
    title: "Soft Geometry",
    description: "Planes, silence, and reflected light.",
    imageUrl: "/images/work2.jpg",
    sideText: {
      eyebrow: "Collection",
      title: "Soft Geometry",
      description: "Planes, silence and reflected light arranged in a restrained composition.",
      align: "before",
    },
    metadata: { artist: "I. Rowan", year: "2025", medium: "Digital C-Print" },
  },
  {
    id: "w-03",
    type: "artwork",
    title: "Threshold #4",
    description: "A corridor inside another corridor.",
    imageUrl: "/images/work3.jpg",
    metadata: { artist: "Noa Lane", year: "2026", medium: "Mixed Media" },
  },
  {
    id: "w-04",
    type: "artwork",
    title: "Monochrome Drift",
    description: "A cloud-like structure in muted tones.",
    imageUrl: "/images/work4.jpg",
    metadata: { artist: "R. Chen", year: "2024", medium: "Photography" },
  },
];

export const DEFAULT_GALLERY_CONFIG: ArtGallerySceneConfig = {
  id: "daylight-galery",
  sceneTitle: "DayLight galery",
  lightingMode: "day",
  infiniteCorridor: true,
  sceneBackgroundColor: GALLERY_TOKENS.scene.defaultBackground,
  sceneFogColor: GALLERY_TOKENS.scene.defaultFog,
  ceilingSpotsEnabled: false,
  ceilingSpotsColor: GALLERY_TOKENS.scene.defaultCeilingSpotsColor,
  ceilingSpotsIntensity: 0.9,
  artworkBacklightEnabled: false,
  artworkBacklightColor: GALLERY_TOKENS.scene.defaultArtworkBacklightColor,
  artworkBacklightIntensity: 1.1,
  enhanceNightReadibility: false,
  scrollStrength: 1,
  mobileDetailsOverlayEnabled: true,
  mobileDetailsBackdropEnabled: true,
  mobileDetailsBackdropIntensity: 1,
  mobileDetailsBackdropHeight: 0.5,
  mobileDetailsButtonPosition: "top-right",
  mobileDetailsModalPosition: "top",
  progressBarPosition: "top",
  progressBarColor: "#909090",
  progressBarOpacity: 0.82,
  progressBarYOffset: 0,
  progressBarHorizontalPadding: 14,
  desktopDetailsPanelSide: "left",
  desktopDetailsPanelWidth: 0.25,
  loopWhiteAfterEndWindow: 0.14,
  loopWhiteStartsBeforeEndWindow: 0.05,
  loopWhiteFadeOutRevealWindow: 0.12,
  loopWhiteFadeOutWindow: 0.22,
  loopProgressAdvanceDuringWhiteFadeOut: 0.18,
  artworkFocusFill: 0.78,
  artworkTurnSmoothness: 0.65,
  artworkTurnKeyframes: 4,
  artworkTurnLeadIn: 0.2,
  camera: {
    fov: CAMERA_DEFAULTS.fov,
    startPosition: [0, CAMERA_DEFAULTS.height, 10],
    height: CAMERA_DEFAULTS.height,
    movementSmoothing: CAMERA_DEFAULTS.movementSmoothing,
    near: CAMERA_DEFAULTS.near,
    far: CAMERA_DEFAULTS.far,
  },
  corridor: {
    width: GALLERY_DEFAULTS.corridor.width,
    height: GALLERY_DEFAULTS.corridor.height,
    segmentLength: GALLERY_DEFAULTS.corridor.segmentLength,
    wallColor: GALLERY_TOKENS.scene.defaultWall,
    floorColor: GALLERY_TOKENS.scene.defaultFloor,
    ceilingColor: GALLERY_TOKENS.scene.defaultCeiling,
    carpetEnabled: GALLERY_DEFAULTS.corridor.carpetEnabled,
    carpetWidth: GALLERY_DEFAULTS.corridor.carpetWidth,
    carpetColor: GALLERY_DEFAULTS.corridor.carpetColor,
    artworkSpacing: GALLERY_DEFAULTS.corridor.artworkSpacing,
    wallThickness: GALLERY_DEFAULTS.corridor.wallThickness,
    artworkInset: GALLERY_DEFAULTS.corridor.artworkInset,
  },
  sceneTitleConfig: {
    fontUrl: "/fonts/helvetiker_regular.typeface.json",
    size: 0.1,
    depth: 0.3,
    maxWidth: 7.2,
    lineHeight: 1.18,
    color: GALLERY_TOKENS.scene.defaultTitle,
    daylightContrastEnabled: true,
    daylightContrastColor: GALLERY_TOKENS.scene.defaultDaylightTitleContrast,
    daylightContrastStrength: 0.3,
    position: [0, 1.75, 3.25],
    maxOpacity: 1,
    fadeStartProgress: 0.1,
    fadeEndProgress: 0.22,
  },
  timings: {
    introDuration: GALLERY_DEFAULTS.timings.introDuration,
    travelDuration: GALLERY_DEFAULTS.timings.travelDuration,
    focusDuration: GALLERY_DEFAULTS.timings.focusDuration,
    returnDuration: GALLERY_DEFAULTS.timings.returnDuration,
  },
  items: DEFAULT_ARTWORKS.map((artwork) => ({ ...artwork })),
  artworks: DEFAULT_ARTWORKS,
};
