import { DEFAULT_GALLERY_CONFIG } from "../config/defaultGalleryConfig";

export type AspectRatioPreset =
  | "auto"
  | "ratio_9_20"
  | "ratio_3_4"
  | "ratio_1_1"
  | "ratio_4_3"
  | "ratio_16_9"
  | "ratio_20_9";

export type PlaygroundInputType =
  | "text"
  | "number"
  | "boolean"
  | "select"
  | "color"
  | "json";

export interface PlaygroundControlOption {
  label: string;
  value: string | number | boolean;
}

export interface PlaygroundControlDefinition {
  key: string;
  path: string;
  label: string;
  description: string;
  section: string;
  inputType: PlaygroundInputType;
  min?: number;
  max?: number;
  step?: number;
  defaultValue: unknown;
  options?: PlaygroundControlOption[];
  rows?: number;
}

export const ASPECT_RATIO_PRESET_OPTIONS: PlaygroundControlOption[] = [
  { label: "Auto", value: "auto" },
  { label: "9:20", value: "ratio_9_20" },
  { label: "3:4", value: "ratio_3_4" },
  { label: "1:1", value: "ratio_1_1" },
  { label: "4:3", value: "ratio_4_3" },
  { label: "16:9", value: "ratio_16_9" },
  { label: "20:9", value: "ratio_20_9" },
];

export const ASPECT_RATIO_PRESET_VALUES: Record<AspectRatioPreset, number | undefined> = {
  auto: undefined,
  ratio_9_20: 9 / 20,
  ratio_3_4: 3 / 4,
  ratio_1_1: 1,
  ratio_4_3: 4 / 3,
  ratio_16_9: 16 / 9,
  ratio_20_9: 20 / 9,
};

export const DEFAULT_CAMERA_ASPECT_PRESET: AspectRatioPreset = "auto";
export const DEFAULT_MOBILE_CAMERA_ASPECT_PRESET: AspectRatioPreset = "ratio_3_4";

const EPSILON = 0.0001;

export const resolveAspectPresetFromRatio = (
  ratio: number | undefined,
  fallback: AspectRatioPreset,
): AspectRatioPreset => {
  if (typeof ratio !== "number" || !Number.isFinite(ratio)) {
    return fallback;
  }

  const presets = Object.entries(ASPECT_RATIO_PRESET_VALUES) as Array<[AspectRatioPreset, number | undefined]>;
  const matched = presets.find(([, value]) => typeof value === "number" && Math.abs(value - ratio) <= EPSILON);
  return matched?.[0] ?? fallback;
};

const cloneDefault = <T>(value: T): T => {
  if (typeof structuredClone === "function") {
    return structuredClone(value);
  }
  return JSON.parse(JSON.stringify(value)) as T;
};

export const PLAYGROUND_CONTROLS: PlaygroundControlDefinition[] = [
  {
    key: "samplePreset",
    path: "__meta.samplePreset",
    label: "Template",
    description: "Carga una configuración base completa para iterar rápido.",
    section: "Runtime",
    inputType: "select",
    defaultValue: DEFAULT_GALLERY_CONFIG.id,
  },
  {
    key: "mobileMode",
    path: "__meta.mobileMode",
    label: "Mobile Mode",
    description: "Fuerza comportamiento móvil del runtime para validación local.",
    section: "Runtime",
    inputType: "boolean",
    defaultValue: false,
  },
  {
    key: "cameraAspectPreset",
    path: "__meta.cameraAspectPreset",
    label: "Aspect Ratio",
    description: "Preset principal de ratio para el viewport de cámara.",
    section: "Runtime",
    inputType: "select",
    options: ASPECT_RATIO_PRESET_OPTIONS,
    defaultValue: DEFAULT_CAMERA_ASPECT_PRESET,
  },
  {
    key: "mobileCameraAspectPreset",
    path: "__meta.mobileCameraAspectPreset",
    label: "Mobile Aspect Ratio",
    description: "Preset de ratio aplicado cuando entra en modo móvil.",
    section: "Runtime",
    inputType: "select",
    options: ASPECT_RATIO_PRESET_OPTIONS,
    defaultValue: DEFAULT_MOBILE_CAMERA_ASPECT_PRESET,
  },
  {
    key: "id",
    path: "id",
    label: "Scene ID",
    description: "Identificador de la escena.",
    section: "Experience",
    inputType: "text",
    defaultValue: DEFAULT_GALLERY_CONFIG.id,
  },
  {
    key: "sceneTitle",
    path: "sceneTitle",
    label: "Scene Title",
    description: "Título narrativo de la experiencia.",
    section: "Experience",
    inputType: "text",
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitle,
  },
  {
    key: "lightingMode",
    path: "lightingMode",
    label: "Lighting Mode",
    description: "Modo global de iluminación del recorrido.",
    section: "Experience",
    inputType: "select",
    options: [
      { label: "contrast", value: "contrast" },
      { label: "day", value: "day" },
    ],
    defaultValue: DEFAULT_GALLERY_CONFIG.lightingMode,
  },
  {
    key: "infiniteCorridor",
    path: "infiniteCorridor",
    label: "Infinite Corridor",
    description: "Activa loop infinito con transición blanca.",
    section: "Experience",
    inputType: "boolean",
    defaultValue: DEFAULT_GALLERY_CONFIG.infiniteCorridor,
  },
  {
    key: "scrollStrength",
    path: "scrollStrength",
    label: "Scroll Strength",
    description: "Sensibilidad de avance/retroceso sobre scroll/touch.",
    section: "Experience",
    inputType: "number",
    min: 0.25,
    max: 8,
    step: 0.05,
    defaultValue: DEFAULT_GALLERY_CONFIG.scrollStrength,
  },
  {
    key: "enhanceNightReadibility",
    path: "enhanceNightReadibility",
    label: "Enhance Night Readibility",
    description: "Eleva la legibilidad en escenas oscuras ajustando luces existentes.",
    section: "Experience",
    inputType: "boolean",
    defaultValue: DEFAULT_GALLERY_CONFIG.enhanceNightReadibility,
  },
  {
    key: "sceneBackgroundColor",
    path: "sceneBackgroundColor",
    label: "Background Color",
    description: "Color de fondo del entorno renderizado.",
    section: "Lighting",
    inputType: "color",
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneBackgroundColor,
  },
  {
    key: "sceneFogColor",
    path: "sceneFogColor",
    label: "Fog Color",
    description: "Color de niebla volumétrica base.",
    section: "Lighting",
    inputType: "color",
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneFogColor,
  },
  {
    key: "ceilingSpotsEnabled",
    path: "ceilingSpotsEnabled",
    label: "Ceiling Spots Enabled",
    description: "Activa focos de techo para reforzar contraste.",
    section: "Lighting",
    inputType: "boolean",
    defaultValue: DEFAULT_GALLERY_CONFIG.ceilingSpotsEnabled,
  },
  {
    key: "ceilingSpotsColor",
    path: "ceilingSpotsColor",
    label: "Ceiling Spots Color",
    description: "Color de los focos de techo.",
    section: "Lighting",
    inputType: "color",
    defaultValue: DEFAULT_GALLERY_CONFIG.ceilingSpotsColor,
  },
  {
    key: "ceilingSpotsIntensity",
    path: "ceilingSpotsIntensity",
    label: "Ceiling Spots Intensity",
    description: "Intensidad de focos de techo.",
    section: "Lighting",
    inputType: "number",
    min: 0,
    max: 4,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.ceilingSpotsIntensity,
  },
  {
    key: "artworkBacklightEnabled",
    path: "artworkBacklightEnabled",
    label: "Artwork Backlight Enabled",
    description: "Activa luz de recorte detrás de artworks.",
    section: "Lighting",
    inputType: "boolean",
    defaultValue: DEFAULT_GALLERY_CONFIG.artworkBacklightEnabled,
  },
  {
    key: "artworkBacklightColor",
    path: "artworkBacklightColor",
    label: "Artwork Backlight Color",
    description: "Color del backlight de artworks.",
    section: "Lighting",
    inputType: "color",
    defaultValue: DEFAULT_GALLERY_CONFIG.artworkBacklightColor,
  },
  {
    key: "artworkBacklightIntensity",
    path: "artworkBacklightIntensity",
    label: "Artwork Backlight Intensity",
    description: "Intensidad del backlight de artworks.",
    section: "Lighting",
    inputType: "number",
    min: 0,
    max: 4,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.artworkBacklightIntensity,
  },
  {
    key: "mobileDetailsOverlayEnabled",
    path: "mobileDetailsOverlayEnabled",
    label: "Mobile Details Overlay",
    description: "Muestra detalle textual en overlay móvil.",
    section: "Mobile Details",
    inputType: "boolean",
    defaultValue: DEFAULT_GALLERY_CONFIG.mobileDetailsOverlayEnabled,
  },
  {
    key: "mobileDetailsBackdropEnabled",
    path: "mobileDetailsBackdropEnabled",
    label: "Mobile Details Backdrop",
    description: "Activa/oculta sombra de fondo del overlay.",
    section: "Mobile Details",
    inputType: "boolean",
    defaultValue: DEFAULT_GALLERY_CONFIG.mobileDetailsBackdropEnabled,
  },
  {
    key: "mobileDetailsBackdropIntensity",
    path: "mobileDetailsBackdropIntensity",
    label: "Backdrop Intensity",
    description: "Intensidad de la sombra detrás del detalle móvil.",
    section: "Mobile Details",
    inputType: "number",
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.mobileDetailsBackdropIntensity,
  },
  {
    key: "mobileDetailsBackdropHeight",
    path: "mobileDetailsBackdropHeight",
    label: "Backdrop Height",
    description: "Altura/proyección vertical del gradiente de backdrop.",
    section: "Mobile Details",
    inputType: "number",
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.mobileDetailsBackdropHeight,
  },
  {
    key: "mobileDetailsButtonPosition",
    path: "mobileDetailsButtonPosition",
    label: "Details Button Position",
    description: "Posición del botón de apertura del detalle móvil.",
    section: "Mobile Details",
    inputType: "select",
    options: [
      { label: "top-right", value: "top-right" },
      { label: "top-left", value: "top-left" },
      { label: "bottom-right", value: "bottom-right" },
      { label: "bottom-left", value: "bottom-left" },
    ],
    defaultValue: DEFAULT_GALLERY_CONFIG.mobileDetailsButtonPosition,
  },
  {
    key: "mobileDetailsModalPosition",
    path: "mobileDetailsModalPosition",
    label: "Details Modal Position",
    description: "Anclaje vertical del modal de detalle móvil.",
    section: "Mobile Details",
    inputType: "select",
    options: [
      { label: "top", value: "top" },
      { label: "bottom", value: "bottom" },
    ],
    defaultValue: DEFAULT_GALLERY_CONFIG.mobileDetailsModalPosition,
  },
  {
    key: "progressBarPosition",
    path: "progressBarPosition",
    label: "Progress Bar Position",
    description: "Anclaje vertical de la barra de progreso.",
    section: "Progress Bar",
    inputType: "select",
    options: [
      { label: "top", value: "top" },
      { label: "bottom", value: "bottom" },
    ],
    defaultValue: DEFAULT_GALLERY_CONFIG.progressBarPosition,
  },
  {
    key: "progressBarColor",
    path: "progressBarColor",
    label: "Progress Bar Color",
    description: "Color principal de la barra de progreso.",
    section: "Progress Bar",
    inputType: "color",
    defaultValue: DEFAULT_GALLERY_CONFIG.progressBarColor,
  },
  {
    key: "progressBarOpacity",
    path: "progressBarOpacity",
    label: "Progress Bar Opacity",
    description: "Opacidad global de la barra de progreso.",
    section: "Progress Bar",
    inputType: "number",
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.progressBarOpacity,
  },
  {
    key: "progressBarYOffset",
    path: "progressBarYOffset",
    label: "Progress Bar Y Offset",
    description: "Desplazamiento vertical en px respecto al borde anclado.",
    section: "Progress Bar",
    inputType: "number",
    min: -160,
    max: 160,
    step: 1,
    defaultValue: DEFAULT_GALLERY_CONFIG.progressBarYOffset,
  },
  {
    key: "progressBarHorizontalPadding",
    path: "progressBarHorizontalPadding",
    label: "Progress Bar Side Padding",
    description: "Padding lateral en px para acortar/expandir la barra.",
    section: "Progress Bar",
    inputType: "number",
    min: 0,
    max: 240,
    step: 1,
    defaultValue: DEFAULT_GALLERY_CONFIG.progressBarHorizontalPadding,
  },
  {
    key: "camera.mobileBreakpointWidth",
    path: "camera.mobileBreakpointWidth",
    label: "Mobile Breakpoint Width",
    description: "Ancho a partir del cual se considera layout móvil.",
    section: "Mobile Details",
    inputType: "number",
    min: 320,
    max: 1600,
    step: 1,
    defaultValue: 820,
  },
  {
    key: "loopWhiteAfterEndWindow",
    path: "loopWhiteAfterEndWindow",
    label: "Loop White After End",
    description: "Ventana blanca tras completar el recorrido.",
    section: "Loop",
    inputType: "number",
    min: 0.02,
    max: 0.45,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.loopWhiteAfterEndWindow,
  },
  {
    key: "loopWhiteStartsBeforeEndWindow",
    path: "loopWhiteStartsBeforeEndWindow",
    label: "Loop White Lead",
    description: "Anticipación de la transición blanca antes del final.",
    section: "Loop",
    inputType: "number",
    min: 0,
    max: 0.45,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.loopWhiteStartsBeforeEndWindow,
  },
  {
    key: "loopWhiteFadeOutRevealWindow",
    path: "loopWhiteFadeOutRevealWindow",
    label: "Loop White Reveal",
    description: "Ventana de revelado al desvanecer blanco.",
    section: "Loop",
    inputType: "number",
    min: 0.03,
    max: 0.45,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.loopWhiteFadeOutRevealWindow,
  },
  {
    key: "loopWhiteFadeOutWindow",
    path: "loopWhiteFadeOutWindow",
    label: "Loop White Fade Out",
    description: "Duración del fade-out de la transición blanca.",
    section: "Loop",
    inputType: "number",
    min: 0.05,
    max: 0.6,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.loopWhiteFadeOutWindow,
  },
  {
    key: "loopProgressAdvanceDuringWhiteFadeOut",
    path: "loopProgressAdvanceDuringWhiteFadeOut",
    label: "Loop Progress Advance",
    description: "Cuánto avanza el progreso durante el fade-out blanco.",
    section: "Loop",
    inputType: "number",
    min: 0,
    max: 0.45,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.loopProgressAdvanceDuringWhiteFadeOut,
  },
  {
    key: "artworkFocusFill",
    path: "artworkFocusFill",
    label: "Artwork Focus Fill",
    description: "Fracción del tramo dedicada al enfoque de obra.",
    section: "Journey Focus",
    inputType: "number",
    min: 0.35,
    max: 0.95,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.artworkFocusFill,
  },
  {
    key: "artworkTurnSmoothness",
    path: "artworkTurnSmoothness",
    label: "Artwork Turn Smoothness",
    description: "Suavidad del giro/seguimiento del foco de obra.",
    section: "Journey Focus",
    inputType: "number",
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.artworkTurnSmoothness,
  },
  {
    key: "artworkTurnKeyframes",
    path: "artworkTurnKeyframes",
    label: "Artwork Turn Keyframes",
    description: "Número de keyframes usados en el tramo de giro.",
    section: "Journey Focus",
    inputType: "number",
    min: 1,
    max: 12,
    step: 1,
    defaultValue: DEFAULT_GALLERY_CONFIG.artworkTurnKeyframes,
  },
  {
    key: "artworkTurnLeadIn",
    path: "artworkTurnLeadIn",
    label: "Artwork Turn Lead In",
    description: "Anticipación del giro antes de foco total.",
    section: "Journey Focus",
    inputType: "number",
    min: 0,
    max: 0.85,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.artworkTurnLeadIn,
  },
  {
    key: "camera.fov",
    path: "camera.fov",
    label: "Camera FOV",
    description: "Ángulo de visión principal.",
    section: "Camera",
    inputType: "number",
    min: 35,
    max: 90,
    step: 0.1,
    defaultValue: DEFAULT_GALLERY_CONFIG.camera.fov,
  },
  {
    key: "camera.startPosition.0",
    path: "camera.startPosition.0",
    label: "Camera Start X",
    description: "Posición inicial de cámara en eje X.",
    section: "Camera",
    inputType: "number",
    min: -20,
    max: 20,
    step: 0.1,
    defaultValue: DEFAULT_GALLERY_CONFIG.camera.startPosition[0],
  },
  {
    key: "camera.startPosition.1",
    path: "camera.startPosition.1",
    label: "Camera Start Y",
    description: "Posición inicial de cámara en eje Y.",
    section: "Camera",
    inputType: "number",
    min: -20,
    max: 20,
    step: 0.1,
    defaultValue: DEFAULT_GALLERY_CONFIG.camera.startPosition[1],
  },
  {
    key: "camera.startPosition.2",
    path: "camera.startPosition.2",
    label: "Camera Start Z",
    description: "Posición inicial de cámara en eje Z.",
    section: "Camera",
    inputType: "number",
    min: -20,
    max: 20,
    step: 0.1,
    defaultValue: DEFAULT_GALLERY_CONFIG.camera.startPosition[2],
  },
  {
    key: "camera.height",
    path: "camera.height",
    label: "Camera Height",
    description: "Altura base para trayectorias de cámara.",
    section: "Camera",
    inputType: "number",
    min: -20,
    max: 20,
    step: 0.1,
    defaultValue: DEFAULT_GALLERY_CONFIG.camera.height,
  },
  {
    key: "camera.movementSmoothing",
    path: "camera.movementSmoothing",
    label: "Camera Movement Smoothing",
    description: "Suavizado del movimiento de cámara.",
    section: "Camera",
    inputType: "number",
    min: 0.01,
    max: 1,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.camera.movementSmoothing,
  },
  {
    key: "camera.near",
    path: "camera.near",
    label: "Camera Near",
    description: "Plano near de la cámara.",
    section: "Camera",
    inputType: "number",
    min: 0.01,
    max: 2,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.camera.near,
  },
  {
    key: "camera.far",
    path: "camera.far",
    label: "Camera Far",
    description: "Plano far de la cámara.",
    section: "Camera",
    inputType: "number",
    min: 50,
    max: 1000,
    step: 1,
    defaultValue: DEFAULT_GALLERY_CONFIG.camera.far,
  },
  {
    key: "corridor.width",
    path: "corridor.width",
    label: "Corridor Width",
    description: "Ancho del pasillo principal.",
    section: "Corridor",
    inputType: "number",
    min: 4,
    max: 20,
    step: 0.1,
    defaultValue: DEFAULT_GALLERY_CONFIG.corridor.width,
  },
  {
    key: "corridor.height",
    path: "corridor.height",
    label: "Corridor Height",
    description: "Altura del pasillo.",
    section: "Corridor",
    inputType: "number",
    min: 2.8,
    max: 12,
    step: 0.1,
    defaultValue: DEFAULT_GALLERY_CONFIG.corridor.height,
  },
  {
    key: "corridor.segmentLength",
    path: "corridor.segmentLength",
    label: "Corridor Segment Length",
    description: "Longitud base de cada módulo del pasillo.",
    section: "Corridor",
    inputType: "number",
    min: 4,
    max: 30,
    step: 0.1,
    defaultValue: DEFAULT_GALLERY_CONFIG.corridor.segmentLength,
  },
  {
    key: "corridor.wallColor",
    path: "corridor.wallColor",
    label: "Wall Color",
    description: "Color base de muros.",
    section: "Corridor",
    inputType: "color",
    defaultValue: DEFAULT_GALLERY_CONFIG.corridor.wallColor,
  },
  {
    key: "corridor.floorColor",
    path: "corridor.floorColor",
    label: "Floor Color",
    description: "Color base del suelo.",
    section: "Corridor",
    inputType: "color",
    defaultValue: DEFAULT_GALLERY_CONFIG.corridor.floorColor,
  },
  {
    key: "corridor.ceilingColor",
    path: "corridor.ceilingColor",
    label: "Ceiling Color",
    description: "Color base del techo.",
    section: "Corridor",
    inputType: "color",
    defaultValue: DEFAULT_GALLERY_CONFIG.corridor.ceilingColor,
  },
  {
    key: "corridor.carpetEnabled",
    path: "corridor.carpetEnabled",
    label: "Carpet Enabled",
    description: "Activa la alfombra central del pasillo.",
    section: "Corridor",
    inputType: "boolean",
    defaultValue: DEFAULT_GALLERY_CONFIG.corridor.carpetEnabled,
  },
  {
    key: "corridor.carpetWidth",
    path: "corridor.carpetWidth",
    label: "Carpet Width",
    description: "Ancho de la alfombra central.",
    section: "Corridor",
    inputType: "number",
    min: 0.12,
    max: 8,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.corridor.carpetWidth,
  },
  {
    key: "corridor.carpetColor",
    path: "corridor.carpetColor",
    label: "Carpet Color",
    description: "Color de la alfombra central.",
    section: "Corridor",
    inputType: "color",
    defaultValue: DEFAULT_GALLERY_CONFIG.corridor.carpetColor,
  },
  {
    key: "corridor.artworkSpacing",
    path: "corridor.artworkSpacing",
    label: "Artwork Spacing",
    description: "Separación entre obras/estaciones en recorrido.",
    section: "Corridor",
    inputType: "number",
    min: 4,
    max: 30,
    step: 0.1,
    defaultValue: DEFAULT_GALLERY_CONFIG.corridor.artworkSpacing,
  },
  {
    key: "corridor.wallThickness",
    path: "corridor.wallThickness",
    label: "Wall Thickness",
    description: "Grosor estructural de los muros.",
    section: "Corridor",
    inputType: "number",
    min: 0.05,
    max: 1,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.corridor.wallThickness,
  },
  {
    key: "corridor.artworkInset",
    path: "corridor.artworkInset",
    label: "Artwork Inset",
    description: "Inset de obra respecto al plano de pared.",
    section: "Corridor",
    inputType: "number",
    min: 0,
    max: 0.5,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.corridor.artworkInset,
  },
  {
    key: "sceneTitleConfig.fontUrl",
    path: "sceneTitleConfig.fontUrl",
    label: "Title Font URL",
    description: "Fuente del título 3D.",
    section: "Title",
    inputType: "text",
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.fontUrl,
  },
  {
    key: "sceneTitleConfig.size",
    path: "sceneTitleConfig.size",
    label: "Title Size",
    description: "Escala del título principal.",
    section: "Title",
    inputType: "number",
    min: 0.3,
    max: 5,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.size,
  },
  {
    key: "sceneTitleConfig.depth",
    path: "sceneTitleConfig.depth",
    label: "Title Depth",
    description: "Profundidad de extrusión del título.",
    section: "Title",
    inputType: "number",
    min: 0.02,
    max: 1,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.depth,
  },
  {
    key: "sceneTitleConfig.maxWidth",
    path: "sceneTitleConfig.maxWidth",
    label: "Title Max Width",
    description: "Ancho máximo de wrapping del título.",
    section: "Title",
    inputType: "number",
    min: 0.8,
    max: 40,
    step: 0.1,
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.maxWidth,
  },
  {
    key: "sceneTitleConfig.lineHeight",
    path: "sceneTitleConfig.lineHeight",
    label: "Title Line Height",
    description: "Interlineado del título multi-línea.",
    section: "Title",
    inputType: "number",
    min: 0.8,
    max: 2.4,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.lineHeight,
  },
  {
    key: "sceneTitleConfig.color",
    path: "sceneTitleConfig.color",
    label: "Title Color",
    description: "Color base del título.",
    section: "Title",
    inputType: "color",
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.color,
  },
  {
    key: "sceneTitleConfig.daylightContrastEnabled",
    path: "sceneTitleConfig.daylightContrastEnabled",
    label: "Title Daylight Contrast",
    description: "Activa capa extra de contraste en modo day.",
    section: "Title",
    inputType: "boolean",
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.daylightContrastEnabled,
  },
  {
    key: "sceneTitleConfig.daylightContrastColor",
    path: "sceneTitleConfig.daylightContrastColor",
    label: "Title Contrast Color",
    description: "Color de contraste del título en day mode.",
    section: "Title",
    inputType: "color",
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.daylightContrastColor,
  },
  {
    key: "sceneTitleConfig.daylightContrastStrength",
    path: "sceneTitleConfig.daylightContrastStrength",
    label: "Title Contrast Strength",
    description: "Intensidad del contraste del título en modo day.",
    section: "Title",
    inputType: "number",
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.daylightContrastStrength,
  },
  {
    key: "sceneTitleConfig.position.0",
    path: "sceneTitleConfig.position.0",
    label: "Title Position X",
    description: "Posición X del título.",
    section: "Title",
    inputType: "number",
    min: -20,
    max: 20,
    step: 0.1,
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.position[0],
  },
  {
    key: "sceneTitleConfig.position.1",
    path: "sceneTitleConfig.position.1",
    label: "Title Position Y",
    description: "Posición Y del título.",
    section: "Title",
    inputType: "number",
    min: -20,
    max: 20,
    step: 0.1,
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.position[1],
  },
  {
    key: "sceneTitleConfig.position.2",
    path: "sceneTitleConfig.position.2",
    label: "Title Position Z",
    description: "Posición Z del título.",
    section: "Title",
    inputType: "number",
    min: -20,
    max: 20,
    step: 0.1,
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.position[2],
  },
  {
    key: "sceneTitleConfig.maxOpacity",
    path: "sceneTitleConfig.maxOpacity",
    label: "Title Max Opacity",
    description: "Opacidad máxima del título.",
    section: "Title",
    inputType: "number",
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.maxOpacity,
  },
  {
    key: "sceneTitleConfig.fadeStartProgress",
    path: "sceneTitleConfig.fadeStartProgress",
    label: "Title Fade Start",
    description: "Progreso donde empieza el fade del título.",
    section: "Title",
    inputType: "number",
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.fadeStartProgress,
  },
  {
    key: "sceneTitleConfig.fadeEndProgress",
    path: "sceneTitleConfig.fadeEndProgress",
    label: "Title Fade End",
    description: "Progreso donde termina el fade del título.",
    section: "Title",
    inputType: "number",
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.sceneTitleConfig.fadeEndProgress,
  },
  {
    key: "timings.introDuration",
    path: "timings.introDuration",
    label: "Intro Duration",
    description: "Duración de fase inicial.",
    section: "Timings",
    inputType: "number",
    min: 0.001,
    max: 8,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.timings.introDuration,
  },
  {
    key: "timings.travelDuration",
    path: "timings.travelDuration",
    label: "Travel Duration",
    description: "Duración base de desplazamiento entre puntos.",
    section: "Timings",
    inputType: "number",
    min: 0.001,
    max: 8,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.timings.travelDuration,
  },
  {
    key: "timings.focusDuration",
    path: "timings.focusDuration",
    label: "Focus Duration",
    description: "Duración de la fase de foco narrativo.",
    section: "Timings",
    inputType: "number",
    min: 0.001,
    max: 8,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.timings.focusDuration,
  },
  {
    key: "timings.returnDuration",
    path: "timings.returnDuration",
    label: "Return Duration",
    description: "Duración de retorno hacia alineación principal.",
    section: "Timings",
    inputType: "number",
    min: 0.001,
    max: 8,
    step: 0.01,
    defaultValue: DEFAULT_GALLERY_CONFIG.timings.returnDuration,
  },
  {
    key: "artworks",
    path: "artworks",
    label: "Artworks JSON",
    description: "Lista completa de artworks en formato JSON.",
    section: "Content",
    inputType: "json",
    rows: 8,
    defaultValue: cloneDefault(DEFAULT_GALLERY_CONFIG.artworks),
  },
  {
    key: "items",
    path: "items",
    label: "Items JSON",
    description: "Lista completa de items (artworks + stational cards).",
    section: "Content",
    inputType: "json",
    rows: 8,
    defaultValue: cloneDefault(DEFAULT_GALLERY_CONFIG.items ?? []),
  },
];
