import type { ArtGallerySceneConfig, ArtworkConfig } from "../types/galleryConfig";
import { DEFAULT_GALLERY_CONFIG } from "../config/defaultGalleryConfig";
import { GALLERY_TOKENS } from "../config/galleryTokens";

export const sampleGalleryConfigs: ArtGallerySceneConfig[] = [
  {
    ...DEFAULT_GALLERY_CONFIG,
    artworks: DEFAULT_GALLERY_CONFIG.artworks.map((artwork) => ({
      ...artwork,
      sideText: undefined,
    })),
    items: DEFAULT_GALLERY_CONFIG.artworks.map((artwork) => ({
      ...artwork,
      type: "artwork" as const,
      sideText: undefined,
    })),
  },
  {
    ...DEFAULT_GALLERY_CONFIG,
    id: "mistery-museum",
    sceneTitle: "Mistery Museum",
    lightingMode: "contrast",
    infiniteCorridor: true,
    sceneBackgroundColor: GALLERY_TOKENS.samples.misteryMuseum.background,
    sceneFogColor: GALLERY_TOKENS.samples.misteryMuseum.fog,
    ceilingSpotsEnabled: true,
    ceilingSpotsColor: GALLERY_TOKENS.samples.misteryMuseum.ceilingSpots,
    ceilingSpotsIntensity: 4,
    artworkBacklightEnabled: true,
    artworkBacklightColor: GALLERY_TOKENS.samples.misteryMuseum.artworkBacklight,
    artworkBacklightIntensity: 4,
    enhanceNightReadibility: true,
    scrollStrength: DEFAULT_GALLERY_CONFIG.scrollStrength,
    loopWhiteAfterEndWindow: 0.08,
    loopWhiteStartsBeforeEndWindow: 0.07,
    loopWhiteFadeOutRevealWindow: 0.12,
    loopWhiteFadeOutWindow: 0.24,
    loopProgressAdvanceDuringWhiteFadeOut: 0.22,
    artworkFocusFill: DEFAULT_GALLERY_CONFIG.artworkFocusFill,
    artworkTurnSmoothness: DEFAULT_GALLERY_CONFIG.artworkTurnSmoothness,
    artworkTurnKeyframes: DEFAULT_GALLERY_CONFIG.artworkTurnKeyframes,
    artworkTurnLeadIn: DEFAULT_GALLERY_CONFIG.artworkTurnLeadIn,
    corridor: {
      ...DEFAULT_GALLERY_CONFIG.corridor,
      wallColor: GALLERY_TOKENS.samples.misteryMuseum.wall,
      floorColor: GALLERY_TOKENS.samples.misteryMuseum.floor,
      ceilingColor: GALLERY_TOKENS.samples.misteryMuseum.ceiling,
      carpetColor: GALLERY_TOKENS.samples.misteryMuseum.carpet,
      carpetWidth: 0.68,
      artworkSpacing: 12,
    },
    sceneTitleConfig: {
      ...DEFAULT_GALLERY_CONFIG.sceneTitleConfig,
      color: GALLERY_TOKENS.samples.misteryMuseum.title,
    },
    artworks: DEFAULT_GALLERY_CONFIG.artworks.map((artwork, index) => ({
      ...artwork,
      id: `m-${index + 1}`,
      side: index % 2 === 0 ? "right" : "left",
      frameColor: GALLERY_TOKENS.samples.misteryMuseum.frame,
      spotlightIntensity: 1.35,
      sideText: artwork.sideText
        ? {
            ...artwork.sideText,
            borderEnabled: true,
            borderColor: GALLERY_TOKENS.samples.misteryMuseum.sideTextBorder,
            borderIntensity: 2.2,
            borderWidth: 0.04,
          }
        : artwork.sideText,
    })),
  },
  {
    ...DEFAULT_GALLERY_CONFIG,
    id: "cabaret-nocturno",
    sceneTitle: "Cabaret Nocturno",
    lightingMode: "contrast",
    infiniteCorridor: true,
    sceneBackgroundColor: "#18060f",
    sceneFogColor: "#2f0f1d",
    ceilingSpotsEnabled: true,
    ceilingSpotsColor: "#ff4f9b",
    ceilingSpotsIntensity: 3.2,
    artworkBacklightEnabled: true,
    artworkBacklightColor: "#ffbb4d",
    artworkBacklightIntensity: 2.6,
    enhanceNightReadibility: true,
    loopWhiteAfterEndWindow: 0.09,
    loopWhiteStartsBeforeEndWindow: 0.06,
    loopWhiteFadeOutRevealWindow: 0.12,
    loopWhiteFadeOutWindow: 0.22,
    loopProgressAdvanceDuringWhiteFadeOut: 0.2,
    corridor: {
      ...DEFAULT_GALLERY_CONFIG.corridor,
      wallColor: "#3f1328",
      floorColor: "#2a101b",
      ceilingColor: "#24111a",
      carpetEnabled: true,
      carpetColor: "#d10f58",
      carpetWidth: 1.2,
      artworkSpacing: 11,
    },
    sceneTitleConfig: {
      ...DEFAULT_GALLERY_CONFIG.sceneTitleConfig,
      color: "#ffe8f3",
      daylightContrastEnabled: false,
      daylightContrastColor: "#5f1f3b",
      daylightContrastStrength: 0.5,
      position: [0, 1.85, 3.15],
    },
    artworks: DEFAULT_GALLERY_CONFIG.artworks.map((artwork, index) => ({
      ...artwork,
      id: `c-${index + 1}`,
      side: index % 2 === 0 ? "left" : "right",
      frameEnabled: false,
      frameColor: "#6e1b40",
      spotlightIntensity: 1.55,
      sideText: artwork.sideText
        ? {
            ...artwork.sideText,
            backgroundColor: "#170810",
            textColor: "#ffdbe9",
            borderEnabled: true,
            borderColor: "#ff6aa8",
            borderIntensity: 2.5,
            borderWidth: 0.05,
          }
        : artwork.sideText,
    })),
  },
  {
    ...DEFAULT_GALLERY_CONFIG,
    id: "nave-nodriza",
    sceneTitle: "Nave Nodriza",
    lightingMode: "contrast",
    infiniteCorridor: true,
    sceneBackgroundColor: "#040a14",
    sceneFogColor: "#0a2136",
    ceilingSpotsEnabled: true,
    ceilingSpotsColor: "#66efff",
    ceilingSpotsIntensity: 4.1,
    artworkBacklightEnabled: true,
    artworkBacklightColor: "#4fb4ff",
    artworkBacklightIntensity: 3.2,
    enhanceNightReadibility: true,
    loopWhiteAfterEndWindow: 0.07,
    loopWhiteStartsBeforeEndWindow: 0.08,
    loopWhiteFadeOutRevealWindow: 0.14,
    loopWhiteFadeOutWindow: 0.26,
    loopProgressAdvanceDuringWhiteFadeOut: 0.23,
    corridor: {
      ...DEFAULT_GALLERY_CONFIG.corridor,
      wallColor: "#12314a",
      floorColor: "#0d1d2f",
      ceilingColor: "#1b3a58",
      carpetEnabled: true,
      carpetColor: "#00e5a8",
      carpetWidth: 0.56,
      artworkSpacing: 16,
    },
    sceneTitleConfig: {
      ...DEFAULT_GALLERY_CONFIG.sceneTitleConfig,
      color: "#d7f7ff",
      daylightContrastEnabled: true,
      daylightContrastColor: "#144060",
      daylightContrastStrength: 0.65,
      position: [0, 1.82, 3.05],
    },
    artworks: DEFAULT_GALLERY_CONFIG.artworks.map((artwork, index) => ({
      ...artwork,
      id: `n-${index + 1}`,
      side: index % 2 === 0 ? "right" : "left",
      frameEnabled: false,
      frameColor: "#1f5f83",
      spotlightIntensity: 1.65,
      sideText: artwork.sideText
        ? {
            ...artwork.sideText,
            backgroundColor: "#081a2b",
            textColor: "#dff9ff",
            borderEnabled: true,
            borderColor: "#55dbff",
            borderIntensity: 2.8,
            borderWidth: 0.05,
          }
        : artwork.sideText,
    })),
  },
  {
    ...DEFAULT_GALLERY_CONFIG,
    id: "portfolio-stations",
    sceneTitle: "Portfolio Stations",
    lightingMode: "contrast",
    infiniteCorridor: true,
    sceneBackgroundColor: "#090d15",
    sceneFogColor: "#111a2a",
    ceilingSpotsEnabled: true,
    ceilingSpotsColor: "#c6d6ff",
    ceilingSpotsIntensity: 2.2,
    artworkBacklightEnabled: true,
    artworkBacklightColor: "#8bb4ff",
    artworkBacklightIntensity: 1.9,
    enhanceNightReadibility: true,
    artworks: DEFAULT_GALLERY_CONFIG.artworks.slice(0, 3).map((artwork, index) => ({
      ...artwork,
      id: `p-${index + 1}`,
      side: index % 2 === 0 ? "left" : "right",
      frameEnabled: false,
      frameColor: "#1c2a3f",
    })),
    items: [
      ...DEFAULT_GALLERY_CONFIG.artworks.slice(0, 1).map<ArtworkConfig>((artwork, index) => ({
        ...artwork,
        type: "artwork" as const,
        id: `p-${index + 1}`,
        side: index % 2 === 0 ? "left" : "right",
        frameEnabled: false,
        frameColor: "#1c2a3f",
      })),
      {
        id: "about-station",
        type: "stational-card" as const,
        variant: "about" as const,
        title: "About Me",
        subtitle: "Creative Director - Barcelona",
        description: "I craft cinematic digital experiences with strong visual rhythm.",
        layout: "image-right" as const,
        image: "/images/work4.jpg",
      },
      {
        id: "contact-station",
        type: "stational-card" as const,
        variant: "contact" as const,
        title: "Let's Work Together",
        description: "Available for selected commissions and long-term collaborations.",
        layout: "text" as const,
        contact: {
          email: "hello@scrollix.gallery",
          location: "Barcelona",
        },
        socialLinks: [
          {
            label: "Behance",
            url: "https://behance.net",
          },
          {
            label: "LinkedIn",
            url: "https://linkedin.com",
          },
        ],
        cta: {
          label: "Start a Project",
          url: "https://example.com/contact",
        },
      },
    ],
  },
  {
    ...DEFAULT_GALLERY_CONFIG,
    id: "creative-director-portfolio",
    sceneTitle: "Creative Direction Portfolio",
    lightingMode: "contrast",
    infiniteCorridor: true,
    sceneBackgroundColor: "#090d15",
    sceneFogColor: "#111a2a",
    ceilingSpotsEnabled: true,
    ceilingSpotsColor: "#c6d6ff",
    ceilingSpotsIntensity: 2.2,
    artworkBacklightEnabled: true,
    artworkBacklightColor: "#8bb4ff",
    artworkBacklightIntensity: 1.9,
    artworkDirectionalKeyLightEnabled: true,
    artworkDirectionalKeyLightColor: "#f3f8ff",
    artworkDirectionalKeyLightIntensity: 0.5,
    artworks: [
      {
        id: "nike-air-max-campaign",
        type: "artwork",
        title: "Nike Air Max Campaign",
        description: "A global campaign celebrating movement, innovation and contemporary culture.",
        imageUrl: "/images/projects/project1.jpg",
        side: "left",
        frameEnabled: false,
        frameColor: "#1c2a3f",
        metadata: {
          artist: "Nike",
          year: "2025",
          medium: "Campaign Direction",
          tags: ["Creative Director"],
        },
      },
      {
        id: "sony-bravia-launch",
        type: "artwork",
        title: "Sony Bravia Launch",
        description: "Product storytelling through light, sound and visual atmosphere.",
        imageUrl: "/images/projects/sony-bravia.jpg",
        side: "right",
        frameEnabled: false,
        frameColor: "#1c2a3f",
        metadata: {
          artist: "Sony",
          year: "2024",
          medium: "Launch Campaign",
          tags: ["Creative Director"],
        },
      },
      {
        id: "adidas-originals",
        type: "artwork",
        title: "Adidas Originals",
        description: "A visual identity refresh inspired by youth culture and urban expression.",
        imageUrl: "/images/projects/adidas-originals.jpg",
        side: "left",
        frameEnabled: false,
        frameColor: "#1c2a3f",
        metadata: {
          artist: "Adidas",
          year: "2024",
          medium: "Brand Refresh",
          tags: ["Creative Director"],
        },
      },
      {
        id: "apple-vision-concept",
        type: "artwork",
        title: "Apple Vision Concept",
        description: "Exploring spatial storytelling for next-generation interfaces.",
        imageUrl: "/images/projects/apple-vision.jpg",
        side: "right",
        frameEnabled: false,
        frameColor: "#1c2a3f",
        metadata: {
          artist: "Concept Project",
          year: "2025",
          medium: "Experience Design",
          tags: ["Creative Director"],
        },
      },
      {
        id: "spotify-reimagined",
        type: "artwork",
        title: "Spotify Reimagined",
        description: "A visual exploration of music discovery and emotional journeys.",
        imageUrl: "/images/projects/spotify-reimagined.jpg",
        side: "left",
        frameEnabled: false,
        frameColor: "#1c2a3f",
        metadata: {
          artist: "Spotify",
          year: "2023",
          medium: "Experience Concept",
          tags: ["Creative Director"],
        },
      },
    ],
    items: [
      {
        id: "nike-air-max-campaign",
        type: "artwork" as const,
        title: "Nike Air Max Campaign",
        description: "A global campaign celebrating movement, innovation and contemporary culture.",
        imageUrl: "/images/projects/project1.png",
        side: "left",
        frameEnabled: false,
        frameColor: "#1c2a3f",
        metadata: {
          artist: "Nike",
          year: "2025",
          medium: "Campaign Direction",
          tags: ["Creative Director"],
        },
      },
      {
        id: "sony-bravia-launch",
        type: "artwork" as const,
        title: "Sony Bravia Launch",
        description: "Product storytelling through light, sound and visual atmosphere.",
        imageUrl: "/images/projects/project2.png",
        side: "right",
        frameEnabled: false,
        frameColor: "#1c2a3f",
        metadata: {
          artist: "Sony",
          year: "2024",
          medium: "Launch Campaign",
          tags: ["Creative Director"],
        },
      },
      {
        id: "adidas-originals",
        type: "artwork" as const,
        title: "Adidas Originals",
        description: "A visual identity refresh inspired by youth culture and urban expression.",
        imageUrl: "/images/projects/project3.png",
        side: "left",
        frameEnabled: false,
        frameColor: "#1c2a3f",
        metadata: {
          artist: "Adidas",
          year: "2024",
          medium: "Brand Refresh",
          tags: ["Creative Director"],
        },
      },
      {
        id: "about-station",
        type: "stational-card" as const,
        variant: "about" as const,
        title: "About Me",
        subtitle: "Stationary Card",
        biography: "I turn brands into stories people feel.",
        manifesto:
          "I am a creative director specializing in brand storytelling, campaign development and immersive digital experiences. Over the past decade I have collaborated with global brands, multidisciplinary teams and independent creators to build visual narratives that connect strategy and emotion.",
        services: [
          "10+ Years - Experience",
          "Brand Storytelling - Strategy and Concept",
          "Campaign Direction - Creative Leadership",
          "Immersive Experiences - Digital and Spatial",
        ],
        references: ["Based in Barcelona, Spain"],
        layout: "text" as const,
        width: 1,
        height: 1,
        depth: 0.04,
        cta: {
          label: "Contact Me",
          url: "#contact",
        },
      },
      {
        id: "apple-vision-concept",
        type: "artwork" as const,
        title: "Apple Vision Concept",
        description: "Exploring spatial storytelling for next-generation interfaces.",
        imageUrl: "/images/projects/project4.png",
        side: "right",
        frameEnabled: false,
        frameColor: "#1c2a3f",
        metadata: {
          artist: "Concept Project",
          year: "2025",
          medium: "Experience Design",
          tags: ["Creative Director"],
        },
      },
      {
        id: "spotify-reimagined",
        type: "artwork" as const,
        title: "Spotify Reimagined",
        description: "A visual exploration of music discovery and emotional journeys.",
        imageUrl: "/images/projects/project5.png",
        side: "left",
        frameEnabled: false,
        frameColor: "#1c2a3f",
        metadata: {
          artist: "Spotify",
          year: "2023",
          medium: "Experience Concept",
          tags: ["Creative Director"],
        },
      },
      {
        id: "contact-station",
        type: "stational-card" as const,
        variant: "contact" as const,
        title: "Let's Work Together",
        subtitle: "Stationary Card",
        manifesto:
          "Available for selected collaborations, consulting and creative leadership roles. Whether you are launching a new brand, developing a global campaign, or exploring an immersive digital experience, I would love to hear about your project.",
        layout: "text" as const,
        width: 2.9,
        height: 2.05,
        depth: 0.04,
        contact: {
          email: "hello@yourstudio.com",
          location: "Barcelona, Spain",
        },
        socialLinks: [
          {
            label: "Behance",
            url: "https://behance.net",
          },
          {
            label: "LinkedIn",
            url: "https://linkedin.com",
          },
          {
            label: "Instagram",
            url: "https://instagram.com",
          },
        ],
        cta: {
          label: "Contact Me",
          url: "mailto:hello@yourstudio.com",
        },
      },
    ],
  },
];
