import type { ArtGallerySceneConfig } from "../types/galleryConfig";
import { DEFAULT_GALLERY_CONFIG } from "../config/defaultGalleryConfig";
import { GALLERY_TOKENS } from "../config/galleryTokens";

export const sampleGalleryConfigs: ArtGallerySceneConfig[] = [
  DEFAULT_GALLERY_CONFIG,
  {
    ...DEFAULT_GALLERY_CONFIG,
    id: "mistery-museum",
    sceneTitle: "Mistery Museum",
    lightingMode: "contrast",
    infiniteCorridor: true,
    sceneBackgroundColor: GALLERY_TOKENS.samples.misteryMuseum.background,
    sceneFogColor: GALLERY_TOKENS.samples.misteryMuseum.fog,
    ceilingSpotsEnabled: true,
    ceilingSpotsColor: GALLERY_TOKENS.samples.misteryMuseum.ceilingSpots,
    ceilingSpotsIntensity: 4,
    artworkBacklightEnabled: true,
    artworkBacklightColor: GALLERY_TOKENS.samples.misteryMuseum.artworkBacklight,
    artworkBacklightIntensity: 4,
    enhanceNightReadibility: true,
    scrollStrength: DEFAULT_GALLERY_CONFIG.scrollStrength,
    loopWhiteAfterEndWindow: 0.08,
    loopWhiteStartsBeforeEndWindow: 0.07,
    loopWhiteFadeOutRevealWindow: 0.12,
    loopWhiteFadeOutWindow: 0.24,
    loopProgressAdvanceDuringWhiteFadeOut: 0.22,
    artworkFocusFill: DEFAULT_GALLERY_CONFIG.artworkFocusFill,
    artworkTurnSmoothness: DEFAULT_GALLERY_CONFIG.artworkTurnSmoothness,
    artworkTurnKeyframes: DEFAULT_GALLERY_CONFIG.artworkTurnKeyframes,
    artworkTurnLeadIn: DEFAULT_GALLERY_CONFIG.artworkTurnLeadIn,
    corridor: {
      ...DEFAULT_GALLERY_CONFIG.corridor,
      wallColor: GALLERY_TOKENS.samples.misteryMuseum.wall,
      floorColor: GALLERY_TOKENS.samples.misteryMuseum.floor,
      ceilingColor: GALLERY_TOKENS.samples.misteryMuseum.ceiling,
      carpetColor: GALLERY_TOKENS.samples.misteryMuseum.carpet,
      carpetWidth: 0.68,
      artworkSpacing: 12,
    },
    sceneTitleConfig: {
      ...DEFAULT_GALLERY_CONFIG.sceneTitleConfig,
      color: GALLERY_TOKENS.samples.misteryMuseum.title,
    },
    artworks: DEFAULT_GALLERY_CONFIG.artworks.map((artwork, index) => ({
      ...artwork,
      id: `m-${index + 1}`,
      side: index % 2 === 0 ? "right" : "left",
      frameColor: GALLERY_TOKENS.samples.misteryMuseum.frame,
      spotlightIntensity: 1.35,
      sideText: artwork.sideText
        ? {
            ...artwork.sideText,
            borderEnabled: true,
            borderColor: GALLERY_TOKENS.samples.misteryMuseum.sideTextBorder,
            borderIntensity: 2.2,
            borderWidth: 0.04,
          }
        : artwork.sideText,
    })),
  },
  {
    ...DEFAULT_GALLERY_CONFIG,
    id: "cabaret-nocturno",
    sceneTitle: "Cabaret Nocturno",
    lightingMode: "contrast",
    infiniteCorridor: true,
    sceneBackgroundColor: "#18060f",
    sceneFogColor: "#2f0f1d",
    ceilingSpotsEnabled: true,
    ceilingSpotsColor: "#ff4f9b",
    ceilingSpotsIntensity: 3.2,
    artworkBacklightEnabled: true,
    artworkBacklightColor: "#ffbb4d",
    artworkBacklightIntensity: 2.6,
    enhanceNightReadibility: true,
    loopWhiteAfterEndWindow: 0.09,
    loopWhiteStartsBeforeEndWindow: 0.06,
    loopWhiteFadeOutRevealWindow: 0.12,
    loopWhiteFadeOutWindow: 0.22,
    loopProgressAdvanceDuringWhiteFadeOut: 0.2,
    corridor: {
      ...DEFAULT_GALLERY_CONFIG.corridor,
      wallColor: "#3f1328",
      floorColor: "#2a101b",
      ceilingColor: "#24111a",
      carpetEnabled: true,
      carpetColor: "#d10f58",
      carpetWidth: 1.2,
      artworkSpacing: 11,
    },
    sceneTitleConfig: {
      ...DEFAULT_GALLERY_CONFIG.sceneTitleConfig,
      color: "#ffe8f3",
      daylightContrastEnabled: false,
      daylightContrastColor: "#5f1f3b",
      daylightContrastStrength: 0.5,
      position: [0, 1.85, 3.15],
    },
    artworks: DEFAULT_GALLERY_CONFIG.artworks.map((artwork, index) => ({
      ...artwork,
      id: `c-${index + 1}`,
      side: index % 2 === 0 ? "left" : "right",
      frameEnabled: true,
      frameColor: "#6e1b40",
      spotlightIntensity: 1.55,
      sideText: artwork.sideText
        ? {
            ...artwork.sideText,
            backgroundColor: "#170810",
            textColor: "#ffdbe9",
            borderEnabled: true,
            borderColor: "#ff6aa8",
            borderIntensity: 2.5,
            borderWidth: 0.05,
          }
        : artwork.sideText,
    })),
  },
  {
    ...DEFAULT_GALLERY_CONFIG,
    id: "nave-nodriza",
    sceneTitle: "Nave Nodriza",
    lightingMode: "contrast",
    infiniteCorridor: true,
    sceneBackgroundColor: "#040a14",
    sceneFogColor: "#0a2136",
    ceilingSpotsEnabled: true,
    ceilingSpotsColor: "#66efff",
    ceilingSpotsIntensity: 4.1,
    artworkBacklightEnabled: true,
    artworkBacklightColor: "#4fb4ff",
    artworkBacklightIntensity: 3.2,
    enhanceNightReadibility: true,
    loopWhiteAfterEndWindow: 0.07,
    loopWhiteStartsBeforeEndWindow: 0.08,
    loopWhiteFadeOutRevealWindow: 0.14,
    loopWhiteFadeOutWindow: 0.26,
    loopProgressAdvanceDuringWhiteFadeOut: 0.23,
    corridor: {
      ...DEFAULT_GALLERY_CONFIG.corridor,
      wallColor: "#12314a",
      floorColor: "#0d1d2f",
      ceilingColor: "#1b3a58",
      carpetEnabled: true,
      carpetColor: "#00e5a8",
      carpetWidth: 0.56,
      artworkSpacing: 16,
    },
    sceneTitleConfig: {
      ...DEFAULT_GALLERY_CONFIG.sceneTitleConfig,
      color: "#d7f7ff",
      daylightContrastEnabled: true,
      daylightContrastColor: "#144060",
      daylightContrastStrength: 0.65,
      position: [0, 1.82, 3.05],
    },
    artworks: DEFAULT_GALLERY_CONFIG.artworks.map((artwork, index) => ({
      ...artwork,
      id: `n-${index + 1}`,
      side: index % 2 === 0 ? "right" : "left",
      frameEnabled: true,
      frameColor: "#1f5f83",
      spotlightIntensity: 1.65,
      sideText: artwork.sideText
        ? {
            ...artwork.sideText,
            backgroundColor: "#081a2b",
            textColor: "#dff9ff",
            borderEnabled: true,
            borderColor: "#55dbff",
            borderIntensity: 2.8,
            borderWidth: 0.05,
          }
        : artwork.sideText,
    })),
  },
];
